services:
  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks:
      - app_network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:3000" 
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge