FROM python:3.10

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry

RUN poetry install --no-dev

COPY src ./src
COPY alembic.ini alembic.ini

EXPOSE 8000

CMD ["sh", "-c", "export PYTHONPATH=$PWD:$PWD/src:$PYTHONPATH && poetry run alembic upgrade head && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]